### ISSUE TITLE
Set WP_ENVIRONMENT_TYPE for the WordPress Configuration

### ISSUE THREAD

**Issue by wpamitkumar** [wp-cli/config-command#112]
Need a functionality to get or set configuration option for WP_ENVIRONMENT_TYPE for WordPress version 5.5. Please check this post: https://make.wordpress.org/core/2020/07/24/new-wp_get_environment_type-function-in-wordpress-5-5/

**Comment by austinginder** [comment]
This can be defined by adding to the `wp-config.php` file. With WP-CLI you can do that like this:

`wp config set WP_ENVIRONMENT_TYPE production`
`wp config set WP_ENVIRONMENT_TYPE development`
`wp config set WP_ENVIRONMENT_TYPE staging`

**Comment by schlessera** [comment]
Yes, just as @austinginder is saying, this can already be done and doesn't need any additional mechanism.
