### ISSUE TITLE
Misconfiguration composer.json (no php version)

### ISSUE THREAD

**Issue by d1sparity-plesk** [wp-cli/config-command#118]
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).

- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

This command doesn't have any PHP requirement, so I expect that PHP version is the same as in wp-cli/wp-cli (for example). 

[WP-CLI](https://packagist.org/packages/wp-cli/wp-cli) declares that it is supported **php: ^5.4 || ^7.0**.

The current version of the command contains [code](https://github.com/wp-cli/config-command/commit/70dbaa2d1480203b75f14ea6c87a9d71a8a9d75d#diff-8c43ee4439224cdb788f81713eb643ad21b61840572cec8399362df9f2ec1795) that only works with PHP 5.6, so I can install an incompatible version on PHP 5.4 via composer.

**Describe how other contributors can replicate this bug**

- Obtain config-command v2.0.7+ and wp-cli v2+
- Try to run any subcommand of config command on php 5.4 or 5.5

> **Fatal error**:  Arrays are not allowed in class constants in ...

**Describe what you would expect as the correct outcome**

I expect that composer.json contains php requirement (for composer to install a compatible version of the package) or this command works on wp-cli requirements.

**Let us know what environment you are running this on** 

php 5.5 or 5.4

**Provide a possible solution**

I have no idea because older versions are affected too.

**Provide additional context/Screenshots**

https://github.com/wp-cli/config-command/commit/70dbaa2d1480203b75f14ea6c87a9d71a8a9d75d#diff-8c43ee4439224cdb788f81713eb643ad21b61840572cec8399362df9f2ec1795

https://packagist.org/packages/wp-cli/wp-cli#v2.4.1
https://packagist.org/packages/wp-cli/config-command#v2.0.7

**Comment by danielbachhuber** [comment]
Thanks for the report, @d1sparity-plesk

PHP 5.6 is the lowest supported version https://github.com/wp-cli/wp-cli/blob/004f90cd6ee9d72eab55f27406341cca9f106224/composer.json#L11
