### ISSUE TITLE
Make clear that --dbname and --dbuser are mandatory when using wp config create

### ISSUE THREAD

**Issue by alberto-marin** [wp-cli/config-command#120]
When using:

`wp core download --locale=en_GB && wp config create`

it returns an error:

```
Error: Parameter errors:
 missing --dbname parameter (Set the database name.)
 missing --dbuser parameter (Set the database user.)
```

The documentation and/or the error message should make clear that those missing parameters are mandatory. 

Even when we use `--skip-check` it returns the same error:

`wp core download --locale=en_GB && wp config create --skip-check`
```
Error: Parameter errors:
 missing --dbname parameter (Set the database name.)
 missing --dbuser parameter (Set the database user.)
```

**Comment by schlessera** [comment]
The [documentation for the `config create` command](https://developer.wordpress.org/cli/commands/config/create/) already shows that these two flags are mandatory, as optional flags are shown in square brackets: `--mandatory` vs `[--optional]`.

This has nothing to do with extra checks that would be affected by `--skip-check`, it is just the basic requirement of running that command.

**Comment by alberto-marin** [comment]
Thank you, I couldn't see anywhere that commands in brackets were optional but that now makes sense, cheers!
