### ISSUE TITLE
Is "wp config" removed?

### ISSUE THREAD

**Issue by tjtate** [wp-cli/config-command#125]
After running this line in my vagrant provision script: 

`wp config set WP_SITEURL "https://$DOMAIN" --allow-root`

I get the following error: 

`Error: 'config' is not a registered wp command. See 'wp help'.`

version: WP-CLI 1.1.0

docs say otherwise: 
https://developer.wordpress.org/cli/commands/config/set/

**Comment by wojsmol** [comment]
Hi 
Current WP-CLI version is 2.4.0.

**Comment by schlessera** [comment]
Yes, please update to a recent version of WP-CLI to get access to the `config` command.

Alternatively, you can try `wp package install wp-cli/config-command`, but I'm not sure this will work on WP-CLI v1.1.0...
