### ISSUE TITLE
Unable to properly set `WP_DEBUG` using `wp config create --extra-php` as of wp cli 2.6.0

### ISSUE THREAD

**Issue by Hlsgs** [wp-cli/config-command#140]
## Bug Report

- [ x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [ x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

As of 2.6.0, code added via the `--extra-php` parameter gets added below the `/* Add any custom values between this line and the "stop editing" line. */` line. Therefore, adding a definition for `WP_DEBUG` there results in a `Constant WP_DEBUG already defined` notice, as it no longer overwrites the default `define( 'WP_DEBUG', false );`.

**Comment by FrozenAlex** [comment]
I have the same issue, I think this [pull request ](https://github.com/wp-cli/config-command/pull/139) broke everything

**Comment by wojsmol** [comment]
@Hlsgs You can use `wp config set WP_DEBUG true --raw` to set `define( 'WP_DEBUG', true );`

**Comment by schlessera** [comment]
I added the `define( 'WP_DEBUG', false );` because it was part of the original WP Core config template.
I agree with @Hlsgs , we should move it below the `{{extra-php}}` section and make it conditional.
