### ISSUE TITLE
`wp config create` : Error Config Create on mysql --no-default --execute

### ISSUE THREAD

**Issue by benyaminl** [wp-cli/config-command#143]
```bash
PS > wp config create --dbname=ecom --dbuser=root --dbpass=
'"mysql --no-defaults --execute="' is not recognized as an internal or external command,
operable program or batch file.
PS > which mysql 
C:/laragon/bin/mysql/mysql-5.7.38-winx64/bin/mysql.exe
```

Is it by design it only works on Linux? I seen the docs talk about windows, but when running config, it doesn't work. It seems broken from the shell_exec or such, because it should work from windows perspective

**Comment by danielbachhuber** [comment]
Thanks for the report, @benyaminl ! 

I just replied on #145, so let's continue the conversation on that issue.
