### ISSUE TITLE
Error on Windows 11 with WP CLI 2.6 and PHP 8.1.6

### ISSUE THREAD

**Issue by symisz** [wp-cli/config-command#145]
I'm using PHP 8.1.6 with wp cli 2.6 and get the following error:
It worked fine before with wp cli 2.4 and an older PHP version.

Here is a section of the command I used. (command is cut here for privacy reasons)

```
wp config create --dbhost="127.0.0.1" --dbuser="....."
```

> '"mysql --no-defaults --execute="' is not recognized as an internal or external command,
> operable program or batch file.

**Comment by danielbachhuber** [comment]
Thanks for the report, @symisz !

Are you able to `wp cli update --nightly` and see if the error reproduces with the latest nightly?

Also, can you share the output of `wp cli info` ?

**Comment by symisz** [comment]
Thanks for your reply @danielbachhuber !

I was able to run `wp cli update --nightly` this time around, wasn't successful before however.
And I get the same error message:

>1/9 --dbname=<dbname>: dev3
2/9 [--dbpass=<dbpass>]:
wp config create --dbhost="..." --dbuser="..." --dbcharset="utf8mb4" --dbcollate="utf8mb4_unicode_ci" --force --dbname="dev3" --dbprefix="wp_"
'"mysql --no-defaults --execute="' is not recognized as an internal or external command,
operable program or batch file.

wp cli info output:
>OS:     Windows NT 10.0 build 22622 (Windows 11) AMD64
Shell:  C:\WINDOWS\system32\cmd.exe
PHP binary:     C:\xampp\php\php.exe
PHP version:    8.1.6
php.ini used:   C:\xampp\php\php.ini
MySQL binary:
MySQL version:
SQL modes:
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       G:\htdocs\dev3
WP-CLI packages dir:
WP-CLI global config:   C:\Users\.../.wp-cli/config.yml
WP-CLI project config:
WP-CLI version: 2.7.0-alpha-38dab66

While this testing has been done on PHP 8.1.6
I was in the midst of reverting back to PHP 7.4, as I read some other users have rumored it to be more stable with WP CLI on Windows.

**Comment by symisz** [comment]
@danielbachhuber WordPress seems to run fine on PHP 8.1.6.
I'm using a package installer called Xampp and it installs the mysql binary to `C:\xampp\mysql\bin`
On my Windows system I have manually added the environment variable and the `wp config create` command worked fine, prior to using PHP 8.1.6 and WP CLI 2.6+.
It worked fine when using Xampp, which _might_ been shipped with PHP 7.2. and I back then I used WP CLI 2.4.0.

It seems the script only targets the UNIX path to the mysql binary: `/usr/bin/env`

**Comment by danielbachhuber** [comment]
@symisz Interesting! Can you share the output for `wp cli info` against WP-CLI v2.5.0/2.6.0 as well?

Here are some changes to `WP_CLI\Utils\run_mysql_command()` in the last few releases:
* https://github.com/wp-cli/wp-cli/pull/5384
* https://github.com/wp-cli/wp-cli/pull/5420
* https://github.com/wp-cli/wp-cli/pull/5546

There was also the introduction of `WP_CLI\Utils\get_mysql_binary_path()`: https://github.com/wp-cli/wp-cli/pull/5386

It seems like the most likely candidate is that `/usr/bin/env mysql` exists in your old environment, and doesn't exist in your new environment.

**Comment by symisz** [comment]
@danielbachhuber I'm getting the same result on PHP 7.4.29

>OS:     Windows NT 10.0 build 22622 (Windows 10) AMD64
Shell:  C:\WINDOWS\system32\cmd.exe
PHP binary:     C:\xampp\php\php.exe
PHP version:    7.4.29
php.ini used:   C:\xampp\php\php.ini
MySQL binary:
MySQL version:
SQL modes:
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       G:\htdocs\dev3
WP-CLI packages dir:
WP-CLI global config:   C:\Users\USERNAME/.wp-cli/config.yml
WP-CLI project config:
WP-CLI version: 2.5.0

>Success: Generated 'wp-config.php' file.

>OS:     Windows NT 10.0 build 22622 (Windows 10) AMD64
Shell:  C:\WINDOWS\system32\cmd.exe
PHP binary:     C:\xampp\php\php.exe
PHP version:    7.4.29
php.ini used:   C:\xampp\php\php.ini
MySQL binary:
MySQL version:
SQL modes:
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       G:\htdocs\dev3
WP-CLI packages dir:
WP-CLI global config:   C:\Users\USERNAME/.wp-cli/config.yml
WP-CLI project config:
WP-CLI version: 2.6.0

>Success: Generated 'wp-config.php' file.

**Comment by danielbachhuber** [comment]
@symisz As it turns out, there was an existing issue for this! https://github.com/wp-cli/wp-cli/issues/5521

I've landed a [couple of changes](https://github.com/wp-cli/wp-cli/issues/5521#issuecomment-1279302645) in the nightly build. Can you run `wp cli update --nightly`, and then see if the issue still exists?

**Comment by symisz** [comment]
@danielbachhuber Thanks for this update! Happily to confirm that it works on PHP 7.4 as well on the latest 8.10, as @mlipe-nxs has mentioned in his post.
Very much appreciated by the effort you and others have put into this!

here is my wp cli info output:
>OS:     Windows NT 10.0 build 22623 (Windows 11) AMD64
Shell:  C:\WINDOWS\system32\cmd.exe
PHP binary:     C:\xampp\php\php.exe
PHP version:    8.1.10
php.ini used:   C:\xampp\php\php.ini
MySQL binary:
MySQL version:
SQL modes:
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       G:\htdocs\dev3
WP-CLI packages dir:
WP-CLI cache dir:       C:\Users\USERNAME/.wp-cli/cache
WP-CLI global config:   C:\Users\USERNAME/.wp-cli/config.yml
WP-CLI project config:
WP-CLI version: 2.8.0-alpha-bd378d0
