### ISSUE TITLE
Get the value of a specific constant or global

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/config-command#15]
As a WP-CLI user, it would be helpful if I could get the value of a specific constant or global out of `wp-config.php`.

The syntax could be `wp config get --constant=DB_NAME` and `wp config get --global=table_prefix`

If I use either `--constant=<constant>` or `--global=<global>`, WP-CLI should simply print the value.

From https://github.com/wp-cli/config-command/pull/14#issuecomment-305191119

**Comment by tmugford** [comment]
That would be a great addition. I often use [jq](https://github.com/stedolan/jq) in combination with `--format=json`, and a usable (if slightly longwinded) workaround is 

`wp config get --format=json | jq '.[] | select(.key == "<name>") | .value' -r`

…where `<name>` is the variable required. Hope that helps anybody looking for a solution in the meantime.

**Comment by danielbachhuber** [comment]
🚢
