### ISSUE TITLE
wp config get return 2048 with unquoted defined value

### ISSUE THREAD

**Issue by FerronN** [wp-cli/config-command#150]
## Bug Report

- [X ] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [X ] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

I have a `wp-config.php` file with the following defined:

`define( 'MYSQL_CLIENT_FLAGS', MYSQLI_CLIENT_SSL );`

when I run this command:

`wp config get "MYSQL_CLIENT_FLAGS" ` I get 2048 returned. When I put single quotes around `MYSQLI_CLIENT_SSL` it returns the value as expected. I would expect the value to be returned without single quotes, because with them the setting doesn't work. The value was set with: `wp config set "MYSQL_CLIENT_FLAGS" "MYSQLI_CLIENT_SSL" --raw`.

I tried all format and type parameters but nothing works.

**WP CLI**
2.7

**Comment by danielbachhuber** [comment]
Thanks for the report, @FerronN !

I'm not 100% sure I understand the bug. Would you be able to put together a pull request with a failing Behat test?

Here is some [guidance on our pull request best practices](https://make.wordpress.org/cli/handbook/contributions/pull-requests/), if it's helpful.

**Comment by ferronsw** [comment]
@danielbachhuber Thank you! I've followed this [guide](https://make.wordpress.org/cli/handbook/contributions/pull-requests/#working-on-a-specific-command-package). But `vendor/bin/wp --info` results in `bash: vendor/bin/wp: No such file or directory`. Am I missing something?

**Comment by danielbachhuber** [comment]
> But `vendor/bin/wp --info` results in `bash: vendor/bin/wp: No such file or directory`. Am I missing something?

@FerronN From which path are you running the command?

This flow should work...

```bash
git clone git@github.com:wp-cli/wp-cli-dev.git
cd wp-cli-dev
composer install
./vendor/bin/wp
```

> Do you have a template for a behat test. I've no experience with it.

The existing tests should be a good point of reference: https://github.com/wp-cli/config-command/tree/main/features

Feel free to stop by the `#cli` channel on [WordPress.org](https://make.wordpress.org/chat/) Slack if you'd like help debugging further.

**Comment by ferronsw** [comment]
@danielbachhuber I executed the command from `~/wp-cli-dev`.

**Comment by ferronsw** [comment]
Fixed after running:

`apt install php-curl php-xml`

**Comment by ferronsw** [comment]
I've added the example.

**Comment by mrsdizzie** [comment]
I believe this happens because `MYSQLI_CLIENT_SSL` exists as an already defined constant with a value of 2048 that originates here:

https://github.com/php/php-src/blob/master/ext/mysqlnd/mysqlnd_enum_n_def.h#L91

and is set here:

 https://github.com/php/php-src/blob/master/ext/mysqli/mysqli_arginfo.h#L1060

**Comment by danielbachhuber** [comment]
@mrsdizzie Great sleuthing! Thanks for looking into it 😊
