### ISSUE TITLE
Test MySQL connection using native PHP functions

### ISSUE THREAD

**Issue by adamziel** [wp-cli/config-command#152]
## Description

Testing the MySQL connection via `new PDO()` or `mysqli_connect()` would make the `config create` command more portable. At the moment, the connection test requires support for a `proc_open` function and a shell `mysql` client. Both are problematic in the context of WebAssembly WordPress Playground.

https://github.com/wp-cli/config-command/blob/965be26705e67dc1438b6a8f81232d73f4e95db4/src/Config_Command.php#L164-L166

**Comment by danielbachhuber** [comment]
Thanks for the suggestion, @adamziel !

Here's where the db check was added originally:https://github.com/wp-cli/wp-cli/pull/484

I suspect the `mysql` executable was used because `wpdb.php` isn't available yet. It should be fine to switch over if we can, though.

**Comment by wojtekn** [comment]
@adamziel @danielbachhuber I opened a PR with this change:

https://github.com/wp-cli/config-command/pull/158

**Comment by adamziel** [comment]
cc @dmsnell
