### ISSUE TITLE
Error: Could not create new 'wp-config.php' file.

### ISSUE THREAD

**Issue by zwzone** [wp-cli/config-command#157]
## Bug Report

- [X] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [ ] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

I ran "wp config create" command, and it provides me an EMPTY wp-config.php file.

**Provide additional context/Screenshots**

<img width="1503" alt="Screen Shot 2023-06-07 at 1 28 11 PM" src="https://github.com/wp-cli/config-command/assets/67689790/2dc034c1-2fc6-4460-927d-b63d15b6dba7">

**Comment by zakaria-wina** [comment]
But When I change my current working directory from root to where I put my wordpress files ( in this case /var/www/html ), the command works fine.
I don't know why, I think the problem is in my machine but I made the same process with the same commands, the error sill occurred.

**Comment by danielbachhuber** [comment]
Hey @zakaria-wina,

The screenshot, it appears the path to `wp-config.mustache` isn't quite what I would expect.

Can you share the results of `wp cli info`?

**Comment by zakaria-wina** [comment]
<img width="1025" alt="Screen Shot 2023-06-10 at 5 32 56 PM" src="https://github.com/wp-cli/config-command/assets/67689790/5953e00b-ae0d-4f20-8c39-8e0fe780c6be">

And BTW, I run wordpress in a debian:buster docker container, and another docker container with the same image for mariadb database.

**Comment by zakaria-wina** [comment]
<img width="1404" alt="Screen Shot 2023-06-10 at 5 43 17 PM" src="https://github.com/wp-cli/config-command/assets/67689790/e1c7fc40-8935-43a5-bcca-dd4e42d37bcd">
As I said in my second comment, I just add this command line ( "cd /var/www/html" ) and everything works fine.

**Comment by danielbachhuber** [comment]
I have no idea 😕

This path is the problem:

<img width="1609" alt="image" src="https://github.com/wp-cli/config-command/assets/36432/bf260fdc-ccd0-465d-a0b1-eb00f81f0592">

It's not a path that WP-CLI can read, so the `wp-config.mustache` template isn't loaded and you end up with the empty `wp-config.php` file.

However, I don't know why it's generating that path.

The offending code is here:

https://github.com/wp-cli/wp-cli/blob/ad16e53f3460f785ed9ef7a82f6f559b10cdd062/php/utils.php#L600-L605

And here's where the caller is running it:

https://github.com/wp-cli/config-command/blob/d06664227981bc9080b5696629ad12be24d169e3/src/Config_Command.php#L204-L205

How are you compiling your PHP? Any special configuration details? Would you be able to put together and share a Docker container that reproduces the issue?

**Comment by Han-Joon-Hyeok** [comment]
I have had the same problem. 
I tried to run 'wp config create' command by using Docker. 

Below is my envionment.

- OS : macOS Catalina v10.15.7
- Docker version : 20.10.17, build 100c701
- Docker compose version : v2.6.1
- Base Image : alpine:3.16

Here is my Dockerfile.

```Dockerfile
# Base image
FROM alpine:3.16

# Install necessary packages
RUN apk add --no-cache \
    dumb-init \
    curl \
    ca-certificates

RUN apk add --no-cache \
    php-fpm \
    php-opcache \
    php-mysqli \
    php-pdo_mysql \
    php-json \
    php-xml \
    php-gd \
    php-dom \
    php-zip \
    php-curl \
    php-openssl \
    php-mbstring \
    php-ctype \
    php-tokenizer \
    php-simplexml \
    php-fileinfo \
    php-exif \
    php-cli \
    php-gd \
    php-phar \
    mariadb-client

# Create directories for wordpress
RUN mkdir -p /var/www/html/wordpress

# Download wp-cli
RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && \
    chmod +x wp-cli.phar && \
    mv wp-cli.phar /usr/bin/wp

# Copy php-fpm configuration file
COPY ./conf/www.conf /etc/php8/php-fpm.d/

RUN chmod +x /usr/bin/dumb-init
COPY ./tools/entrypoint.sh /entrypoint.sh

# Expose port 9000 for php-fpm
EXPOSE 9000

# Start dumb-init for PID 1
ENTRYPOINT ["/usr/bin/dumb-init", "--"]

# Start php-fpm in the foreground
CMD ["/bin/sh", "entrypoint.sh"]

```

And here is `entrypoint.sh`.

```shell
#!/bin/sh

# Update WP-CLI to the latest stable release.
wp cli update

# Download and extracts WordPress core files to the specified path.
wp core download --allow-root --path="$WP_PATH"

# Generates a wp-config.php file.
wp config create --dbname="$MARIA_DB_DATABASE" --dbuser="$MARIA_DB_USER" \
				 --dbpass="$MARIA_DB_PASSWORD" --dbhost="$MARIA_DB_HOST" \
				 --path="$WP_PATH"

# Creates the WordPress tables in the database using the URL, title, and default admin user details provided
wp core install --allow-root --url="$WP_DOMAIN" --title="$WP_TITLE" \
				--admin_user="$WP_ADMIN_USER" --admin_password="$WP_ADMIN_PWD" \
				--admin_email="$WP_ADMIN_EMAIL" --skip-email --path="$WP_PATH"

# Creates a new user
wp user create "$WP_USER" "$WP_USER_EMAIL" --user_pass="$WP_USER_PWD" \
				--path="$WP_PATH"
	
# Set ownership of WordPress files to www-data
adduser -D -S -G www-data www-data
chown -R www-data:www-data /var/www/html/wordpress

# Execute PHP FastCGI in foreground
php-fpm8 -F
```

These files worked well in May, 2023.
But I added `WORKDIR` directive in Dockerfile like below to successfully run `wp config create`.

```Dockerfile
...

# Expose port 9000 for php-fpm
EXPOSE 9000

# Start dumb-init for PID 1
ENTRYPOINT ["/usr/bin/dumb-init", "--"]

# Here, I added 'WORKDIR' directive
WORKDIR /var/www/html/wordpress

# Start php-fpm in the foreground
CMD ["/bin/sh", "/entrypoint.sh"] # I replaced it into absoulte path according to WORKDIR. 
```

I don't know why this method works.
I'm really curious about it.
