### ISSUE TITLE
Add "wp config true" command to assert a config value is truthy

### ISSUE THREAD

**Issue by pwtyler** [wp-cli/config-command#159]
## Feature Request

- [X] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).

**Describe your use case and the problem you are facing**

Today with WP-CLI I can check if a value is set with `wp config has`, and get its value with `wp config get`, but if I want to check if the value is true, I still need to assert with a bash test, like `[[ "$(wp config get FOO)" == 1 ]]`.

`wp config ...` is useful because it parses wp-config, but does not bootstrap WordPress. At times, it is useful to check these values without loading WordPress. Otherwise, this can be accomplished (at least for constants) with `wp eval 'exit((defined("FOO") && FOO) ? 0 : 1);'`

A clear and concise description of what you are actually trying to do, and in what way the current version of WP-CLI is not up to the task.

**Describe the solution you'd like**

`wp config true <name>` would assert if a config value is “truthy”, and exit non-zero if it is false. In this way, we could use exit codes to simplify our tests to something like `if wp config true FOO; then ...`

This also lets us sidestep PHP notices getting captured per https://github.com/wp-cli/wp-cli/issues/5809.

When I get the time, I intend to PR an attempt at this...

**Comment by danielbachhuber** [comment]
Thanks for the suggestion, @pwtyler !

I don't love the idea of adding a single purpose command like `wp config true` because it raises a couple of tricky questions:
1. Are we inspecting `FOO === true` or `FOO == true` ?
2. Do we also need `wp config false`, and type checks like `wp config number`?

I totally understand what you're trying to do, though.

As an alternative to consider, what about `wp config is`?

```
$ head -n 3 wp-config.php
<?php

define( 'FOO', 1 );
$ wp config is truthy FOO
$ echo $?
0
$ wp config is true FOO
$ echo $?
1
$ wp config is integer FOO
$ echo $?
0
$ wp config is string FOO
$ echo $?
1
```

@wp-cli/committers Any ideas?

**Comment by pwtyler** [comment]
Specifically with `wp config false` I would just use `! wp config is true` but I see your point 😁 

Flexibility/expandability of `config is` makes a lot of sense to me.

There's probably some careful consideration re: == vs === since `config get` does some casting with bool values already, we'll want to be consistent.

**Comment by swissspidy** [comment]
> Otherwise, this can be accomplished (at least for constants) with `wp eval 'exit((defined("FOO") && FOO) ? 0 : 1);'`

Would you need this for something other than constants?

> As an alternative to consider, what about `wp config is`?

I'd say most of the time constants in `wp-config.php` are either strings or booleans; integers are less common. I don't see the use case for checking whether a const is a string or an int.
So only the `is truthy`/`is true` check seems useful to me.

**Comment by danielbachhuber** [comment]
> I'd say most of the time constants in `wp-config.php` are either strings or booleans; integers are less common. I don't see the use case for checking whether a const is a string or an int.
> So only the `is truthy`/`is true` check seems useful to me.

Fair enough. I'm open to just having an `is true` command. I think I'd prefer `wp config is-true` vs. `wp config true` because the former makes the command's intent a bit more obvious.

**Comment by scottbuscemi** [comment]
A PR was submitted, would love to chat about this tomorrow at Contributor Day :)

**Comment by danielbachhuber** [comment]
@scottbuscemi Sounds great, see you soon!
