### ISSUE TITLE
`wp config set` fails to update string values due to empty line comments

### ISSUE THREAD

**Issue by johnrom** [wp-cli/config-command#170]
In PHP 8.0, 8.1, 8.2, `wp config set` fails to update string values that contain double-slashes when there are empty line comments in `wp-config`.

See the upstream issue: https://github.com/wp-cli/wp-config-transformer/issues/47

**Comment by danielbachhuber** [comment]
Fixed up by https://github.com/wp-cli/wp-config-transformer/pull/48
