### ISSUE TITLE
Improve message for config shuffle-salts result

### ISSUE THREAD

**Issue by ernilambar** [wp-cli/config-command#173]
## Bug Report

- [✓] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [✓] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

We could improve message of **wp config shuffle-salts** command when key does not exist.

`wp config shuffle-salts WP_CACHE_KEY_SALT`

```
Warning: Could not shuffle the unknown key 'WP_CACHE_KEY_SALT'.
Success: Shuffled the salt keys.
```

**Comment by danielbachhuber** [comment]
> We could improve message of **wp config shuffle-salts** command when key does not exist.

@ernilambar To clarify, what would be your suggested improvement?

**Comment by ernilambar** [comment]
May be we can utilize `report_batch_operation_results()`:

`wp config shuffle-salts WP_CACHE_KEY_SALT`


```
Warning: Could not shuffle the unknown key 'WP_CACHE_KEY_SALT'.
Error: No configs shuffled.
```

`wp config shuffle-salts WP_CACHE_KEY_SALT NONCE_SALT`

```
Warning: Could not shuffle the unknown key 'WP_CACHE_KEY_SALT'.
Error: Only shuffled 1 of 2 configs.
```

**Comment by ernilambar** [comment]
@danielbachhuber Should it be `Error: Only shuffled 1 of 2 configs.` or `Success: Shuffled 1 of 2 configs (1 skipped).`?

**Comment by danielbachhuber** [comment]
@ernilambar The latter, I think

**Comment by ernilambar** [comment]
@danielbachhuber I have noticed `contributor-day` tag in several issues. Does that mean issues should be kept for Contributor Day to be fixed?

**Comment by danielbachhuber** [comment]
@ernilambar No, only that it's a good issue for contributor day if it's still open at that time.
