### ISSUE TITLE
How to use remote MySQL/MariaDB server with custom Port using wp config create command?

### ISSUE THREAD

**Issue by joglomedia** [wp-cli/config-command#190]
How to use remote MySQL/MariaDB server with custom Port using `wp config create` command?

**Comment by mrsdizzie** [comment]
GitHub issues are for bug tracking, enhancements, etc., not general support and debugging. General support can be found in the #cli channel on [WordPress.org Slack](https://make.wordpress.org/chat/).

That being said, you can set the port as part of the host string:

`wp config create --dbname=testing --dbuser=wp --dbpass=securepswd --dbhost=localhost:1234`
