### ISSUE TITLE
Create `wp config get` to list configuration defined in parsed wp-config.php

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/config-command#2]
As a WordPress developer, it would be helpful to have a `wp config get` command to list configuration defined in parsed wp-config.php

This command could contain both constants and PHP global variables defined in `wp-config.php`. We can take a similar approach to `WP_CLI\Runner` in identifying this data:

```
// Load wp-config.php code, in the global scope
$wp_cli_original_defined_vars = get_defined_vars();
eval( $this->get_wp_config_code() );
foreach( get_defined_vars() as $key => $var ) {
	if ( array_key_exists( $key, $wp_cli_original_defined_vars ) || 'wp_cli_original_defined_vars' === $key ) {
		continue;
	}
	global $$key;
	$$key = $var;
}
```

Previously https://github.com/wp-cli/wp-cli/issues/3831

**Comment by rahul3883** [comment]
@danielbachhuber As the `wp_config.php` is already included in `WP_CLI\Runner` using `eval( $this->get_wp_config_code() )`, how will we get constants using the above approach ?

**Comment by danielbachhuber** [comment]
> As the wp_config.php is already included in WP_CLI\Runner using eval( $this->get_wp_config_code() ), how will we get constants using the above approach ?

If you add `@when before_wp_load`, then your command will run before WordPress is loaded, and you can call wp-config.php yourself.

**Comment by rahul3883** [comment]
How should the output format be?
Should I use `\WP_CLI\Formatter::display_items` or `Utils\mustache_render` like we do when we hit `wp help` ?

**Comment by danielbachhuber** [comment]
I think `\WP_CLI\Formatter::display_items` is likely the way to go, as that will give the user the option to render in table, CSV, JSON, etc.
