### ISSUE TITLE
Feature Request: Return single values from config when last parameter exists in config

### ISSUE THREAD

**Issue by onnimonni** [wp-cli/config-command#23]
**What I tried to do**
I tried to get a single config variable with `wp config get`
```
$ wp config get DB_PORT
```

**What I expected as result:**
```
$ wp config get DB_PORT
3306
```

**What I got instead:**
```
$ wp config get DB_PORT
Error: Too many positional arguments: DB_PORT
```

**Comment by danielbachhuber** [comment]
Thanks for the suggestion, @onnimonni.

This is currently possible, but the syntax is a little different:

```
$ wp config get --constant=DB_HOST
localhost
```

It was implemented in #16, which hasn't made it into a WP-CLI release yet. You'll need to update to the latest nightly to gain access: `wp cli update --nightly`
