### ISSUE TITLE
Allow using own template for `wp-config.php`

### ISSUE THREAD

**Issue by evilebottnawi** [wp-cli/config-command#28]
I use `env` variables where storing secret data (example `DB_NAME`, `DB_USER`, `AUTH_KEY` and etc) and want to use `define( 'DB_NAME', getenv('DB_NAME') );`. 

It will be great if i can to use own template for `wp-config.php`.

**Comment by miya0001** [comment]
Hi @evilebottnawi 

Thanks for suggestion. :)

Can you please post this idea to the issue on wp-cli/ideas?
https://github.com/wp-cli/ideas/issues

We want to talk about new idea in the wp-cli/ideas.

Thanks!
