### ISSUE TITLE
Error: Could not create new 'wp-config.php' file.

### ISSUE THREAD

**Issue by kporembinski** [wp-cli/config-command#31]
Hello!

I have strange problem. I can't create new wp-config.php file. I'm getting error which is probably related to code:

```
$bytes_written = file_put_contents( ABSPATH . 'wp-config.php', $out );
		if ( ! $bytes_written ) {
			WP_CLI::error( "Could not create new 'wp-config.php' file." );
		} else {
			WP_CLI::success( "Generated 'wp-config.php' file." );
		}
```
**Error:**
```
[06:09:35] [root@a1 tcwp]# ./wp-cli --allow-root config create --dbname=test --dbuser=test--force --skip-check --debug
Debug (bootstrap): No readable global config found (0.097s)
Debug (bootstrap): No project config found (0.098s)
Debug (bootstrap): argv: ./wp-cli --allow-root config create --dbname=test --dbuser=test --force --skip-check --debug (0.098s)
Debug (bootstrap): ABSPATH defined: /var/www/tcwp/ (0.099s)
Debug (bootstrap): Running command: config create (0.1s)
Error: Could not create new 'wp-config.php' file.
```

In error_log I have found:
```
PHP Warning:  file_get_contents(phar://wp-cli.phar/templates/phar://wp-cli/vendor/wp-cli/config-command/templates/wp-config.mustache): failed to open stream: phar error: "templates/phar:/wp-cli/vendor/wp-cli/config-command/templates/wp-config.mustache" is not a file in phar "wp-cli.phar" in phar:///home/mateuszdemo/public_html/wp-cli/php/utils.php on line 457
```

**wp-cli** is generating empty file. I don't know why it is not working. I have tested this on:

**System:** CentOS release 6.9 (Final)

**PHP** (without suhosin):
```
PHP 7.1.9 (cli) (built: Sep 11 2017 16:59:11) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.9, Copyright (c) 1999-2017, by Zend Technologies
```
**WordPress:** 4.8.2

**Comment by kporembinski** [comment]
It is working when I'm using wp-cli.phar not wp-cli or wp name for command.

**Comment by danielbachhuber** [comment]
Hi @kporembinski,

GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. For support options, please review http://wp-cli.org/#support

**Comment by ryotsun** [comment]
On my environment, macOS Sierra, was also able to replicate it.
But only in the following environment, I could not replicate it.
It's been generated `wp-config.php` correctly.

Use `config` command from the latest `config-command` repository.

```
$ ./wp --info
PHP binary:	/usr/local/Cellar/php71/7.1.8_20/bin/php
PHP version:	7.1.8
php.ini used:	/usr/local/etc/php/7.1/php.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/Users/xxxxx/wp-cli/config-command/wp
WP-CLI packages dir:	/Users/xxxxx/.wp-cli/packages/
WP-CLI global config:	
WP-CLI project config:	/Users/xxxxx/wp-cli/config-command/wp-cli.yml
WP-CLI version:	1.4.0-alpha-f29861c
```

Btw, I guess it contains another bug.
`wp-config.php` will be made as a blank file after this error occurred.
> Error: Could not create new 'wp-config.php' file.

**Comment by danielbachhuber** [comment]
I think this is a duplicate of https://github.com/wp-cli/wp-cli/issues/4689#issuecomment-366428642

**Comment by kwhat** [comment]
I am not sure how related this is to #4689 but it is definitely a bug and should have been addressed not dismissed.

**Comment by andrewjmead** [comment]
I just ran into this one today.

It looks like it doesn't care what the file's name is, but it must have the `phar` extension. I was able to rename it without issue, but removing the extension caused the same error that was reported 7 years ago:

```
Error: Could not create new 'wp-config.php' file.
```
