### ISSUE TITLE
Config parser does not include dependencies

### ISSUE THREAD

**Issue by hakre** [wp-cli/config-command#32]
One of my wp-config.php files makes a (legitimate) `add_filter()` call, however wp-cli can't handle it:

~~~
➜  PhpstormProjects wp --ssh=hakre config get --format=json | jq .
PHP Fatal error:  Uncaught Error: Call to undefined function add_filter() in /home/hakre/.config/composer/vendor/wp-cli/config-command/src/Config_Command.php(250) : eval()'d code:93
Stack trace:
#0 /home/hakre/.config/composer/vendor/wp-cli/config-command/src/Config_Command.php(250): eval()
#1 [internal function]: Config_Command->get(Array, Array)
#2 /home/hakre/.config/composer/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php(87): call_user_func(Array, Array, Array)
#3 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
#4 /home/hakre/.config/composer/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/Subcommand.php(421): call_user_func(Object(Closure), Array, Array)
#5 /home/hakre/.config/composer/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(336): WP_CLI\Dispatcher\Subcommand->invoke(Array, Array, Array)
#6 /home/hakre/.config/composer/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(343): WP_CLI\Runner->run_command(Array, Array)
#7 /home/hakre/.config/composer/vendor/wp-cli/wp-cli/php/WP_C in /home/hakre/.config/composer/vendor/wp-cli/config-command/src/Config_Command.php(250) : eval()'d code on line 93
~~~

**Comment by danielbachhuber** [comment]
> One of my wp-config.php files makes a (legitimate) `add_filter()` call

Can you share your use of `add_filter()`? Are you positive it's actually working?

`add_filter()` isn't defined before `wp-settings.php` is loaded, and `wp-settings.php` executes the entire bootstrap process, so I'm not quite sure why you think this is legitimate. Traditionally, we recommend using an mu-plugin if you want to mandate a particular filter or action.

**Comment by danielbachhuber** [comment]
> `wp-settings.php` executes the entire bootstrap process, so I'm not quite sure why you think this is legitimate.

Oh. I forgot about `wp-load.php`. `wp-settings.php` loads dependencies but doesn't render the template.

Regardless, you should use a mu-plugin for your filter instead. `wp-config.php` sez:

> /* That's all, stop editing! Happy blogging. */

We're not going to support edits beyond that line.

**Comment by hakre** [comment]
I already moved it into an mu-plugin, I was just following some edit suggestion so this might be more common, but I can't say so did at least report it. I'm fine with the workaround for the moment.

**Comment by danielbachhuber** [comment]
> I was just following some edit suggestion so this might be more common, but I can't say so did at least report it.

No worries, I appreciate you taking the time.

> I'm fine with the workaround for the moment.

Sounds good.
