### ISSUE TITLE
env: mysql: No such file or directory

### ISSUE THREAD

**Issue by dylannirvana** [wp-cli/config-command#33]
Getting this error `env: mysql: No such file or directory` when I attempt `wp config create` . I am using MAMP and otherwise everything seems to be working fine. The plan was to `wp core download` , `wp config create` , `wp core install ` .

**Comment by danielbachhuber** [comment]
Hi @dylannirvana,

GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. Bug reports need to be reproducible with a fresh WordPress install. If your issue only reproduces in your environment, then it's likely specific to your environment. For support options, please review http://wp-cli.org/#support
