### ISSUE TITLE
Consider renaming `wp config get` to `wp config list`

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/config-command#41]
In using `wp config get` some, I think @schlessera was right (#14). `wp config get` would be better off as `wp config list`. We can simply add a shim pointing the former to the latter.

Worth changing at this point?

**Comment by gitlost** [comment]
Sounds reasonable to me!

**Comment by schlessera** [comment]
As this is a more recent command, I don't think there's lots of scripting happening with it already, so I don't see an issue with changing this around, and we should then do it sooner, rather than later.

We'll have to make sure we add a corresponding notice in the release notes.

**Comment by gitlost** [comment]
Close via https://github.com/wp-cli/config-command/pull/42
