### ISSUE TITLE
Default `--type=<type>` to 'constant'

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/config-command#47]
Given the majority use-case for the `wp-config.php` file is to act as a store of constants, it would be helpful to default `--type=<type>` to 'constant'.

**Comment by fjarrett** [comment]
I agree, it's a safe assumption and makes sense to do.

**Comment by schlessera** [comment]
That's actually how I started out implementing this command.
We discussed this (https://github.com/wp-cli/config-command/pull/44#discussion_r164257850), and the conclusion so far was that defaulting to a constant makes the command non-deterministic.

But I generally agree, and think that sane defaults might be preferable here, given the majority in this case is probably 95%+.
