### ISSUE TITLE
wp config has -  Does not return response

### ISSUE THREAD

**Issue by josephgagliardi** [wp-cli/config-command#50]
Using wp-cli 1.5.0 on a multisite instance from a root user with flag --allow-root and full path to wp install specified - I do not receive any response from calling this command either for settings known not to exist in wp-config.php or for those known to exist.

**Comment by danielbachhuber** [comment]
Hi @josephgagliardi,

Can you [follow our bug reporting guidelines](https://make.wordpress.org/cli/handbook/bug-reports/) and share sufficient steps to reproduce the issue?

**Comment by schlessera** [comment]
@josephgagliardi `wp config has` does not produce any output. Instead, it returns a shell exit code, so that you can easily use it in conditional checks in your shell scripts.

You can verify the exit code by following your command immediately with `echo $?`:
```
$ wp config has WP_DEBUG
$ echo $?
1

# Exit code `0` => variable or constant was found
# Exit code `1` => variable or constant was NOT found
```
