### ISSUE TITLE
wp config create - Too many positional arguments

### ISSUE THREAD

**Issue by adampatterson** [wp-cli/config-command#55]
Ubuntu 14
CLI 1.5
PHP 5.5.9

This might be my lack of knowledge in the command line.

**But**

```
wp config create --dbname=db_name --dbuser=username --dbpass=password --dbhost='127.0.0.1'
```
will result in Too many positional arguments

```
wp config create --dbname=db_name --dbuser='username' --dbpass='password' --dbhost='127.0.0.1'
```

Placing DB user, password, and host in single quotes worked. The same goes for the `core install` command.

**I didn't see this in any of the docs or the CLI help text.**

https://developer.wordpress.org/cli/commands/config/create/
https://developer.wordpress.org/cli/commands/core/install/

**Comment by schlessera** [comment]
@adampatterson This is just part of the normal shell behavior.
Some characters have a special meaning, like for example the "space" character to separate parameters.

If you want to use such characters inside of a value, you have to "quote" the value to let the shell know that it should just accept the characters as part of the value, instead of interpreting them.

So, `--username=schlessera` would work, whereas `--username=Alain Schlesser` would not work. The shell will see two arguments in that case: `--username=Alain` & `Schlesser`. To let the shell know that it should not interpret the "space" character, you put the value in quotes: `--username="Alain Schlesser"` or `--username='Alain Schlesser'`.

**Comment by adampatterson** [comment]
OK cool, But is this expected for usernames and passwords? I didn't have any spaces and it still had issues. Unless the wrapping the dbhost fixed it and I added single quotes to the rest of the arguments.

**Comment by schlessera** [comment]
There are other characters that need to be quoted or escaped as well. The exact list of characters depends on the shell and environment you're using.

Here's a non-exhaustive list of characters that generally need to be escaped or quoted in the shell:
```
!"$&'()*,:;<=>?@[\]^`{|}
```

**Comment by adampatterson** [comment]
Thanks for the tips/help! 

My passwords did contain special characters so it makes sense then.

**Comment by RewriteThis** [comment]
I just got this error trying to restrict posts to just those with an ID less than something. I used ID<##

**Comment by hmbashar** [comment]
You cannot use spaces in a title or text. Instead, you can use a hyphen (-) like WP-CLI-Test, or you can use quotation marks like "WP CLI Test". Please check the attached file for reference.
![Screenshot at Jun 25 12-33-11 PM](https://github.com/wp-cli/config-command/assets/7321834/85983a82-acc7-47f3-bb93-897e533a8256)

**Comment by codewizard13** [comment]
> You cannot use spaces in a title or text. Instead, you can use a hyphen (-) like WP-CLI-Test, or you can use quotation marks like "WP CLI Test". Please check the attached file for reference.

Having similar issue. I know this is how it is **_supposed to work_**, but neither using single quotes, nor double quotes, nor escaping spaces manually with backslashes worked. Here are some permutations of my `wp core install` command (none worked):

**With no escaping:**

```sh
wp core install --title=EH SSH Install Test --admin_user=myadmin admin_email=support@mysite.com --prompt=admin_password < admin_password.txt --color
```

**With quoted escaped double quotes:**

```sh
wp core install --title="\"EH SSH Install Test\"" --admin_user=myadmin admin_email=support@mysite.com --prompt=admin_password < admin_password.txt --color
```

**With single quotes:**

```sh
wp core install --title='EH SSH Install Test' --admin_user=myadmin admin_email=support@mysite.com --prompt=admin_password < admin_password.txt --color
```

**With double quotes:**

```sh
wp core install --title="EH SSH Install Test" --admin_user=myadmin admin_email=support@mysite.com --prompt=admin_password < admin_password.txt --color
```

**Comment by d-damien** [comment]
@schlessera  Bug is still current. It should work with quotes.
