### ISSUE TITLE
Issue writing change when previous line ends with a //comment

### ISSUE THREAD

**Issue by mrsdizzie** [wp-cli/config-command#57]
Not sure if this belongs here or with wp-config-transformer, but I've encountered an issue when trying to modify a line that comes directly after a line ending with a //comment with no newline in between.

Example configuration block:

```
<?php

// ** MySQL settings - You can get this info from your web host ** //
/** The name of the database for WordPress */
define('WP_CACHE', true); //Added by WP-Cache Manager
define( 'WPCACHEHOME', '/var/www/html/ex/example.com/wp-content/plugins/wp-super-cache/' ); //Added by WP-Cache Manager
```

```
wp config get WPCACHEHOME
/var/www/html/ex/example.com/wp-content/plugins/wp-super-cache/

wp config set WPCACHEHOME test
Success: Updated the constant 'WPCACHEHOME' in the 'wp-config.php' file with the value 'test'.

wp config get WPCACHEHOME
/var/www/html/ex/example.com/wp-content/plugins/wp-super-cache/
```

If I either:
 * Remove the  //Added by WP-Cache Manager comment
 * Put a newline between the WP_CACHE and WPCACHEHOME line

Then it works as expected. This happens with anything that modifies (such as delete) and not just with the set command. Some further testing shows that the file is never opened for writing when this happens, despite being returned as successfully changed:

```
strace -e open,close wp config delete WPCACHEHOME 2>&1 |grep wp-config.php

open("/var/www/html/ex/example.com/test/wp-config.php", O_RDONLY|O_LARGEFILE) = 4
open("/var/www/html/ex/example.com/test/wp-config.php", O_RDONLY|O_LARGEFILE) = 4
open("/var/www/html/ex/example.com/test/wp-config.php", O_RDONLY|O_LARGEFILE) = 4
Success: Deleted the constant 'WPCACHEHOME' from the 'wp-config.php' file.

wp config get WPCACHEHOME
/var/www/html/ex/example.com/wp-content/plugins/wp-super-cache/
```
Using PHP 7.0.29 and WP CLI 1.5.0

**Comment by fjarrett** [comment]
I was able to reproduce and the issue is coming from the transformer. I will submit a PR with the fix later tonight.
