### ISSUE TITLE
wp config create results in broken wp-config.php

### ISSUE THREAD

**Issue by pixolin** [wp-cli/config-command#61]
The command `wp config create --dbname=testwpcli --dbuser=root --dbpass=root` results in a broken `wp-config.php` as the word `Array` in inserted above `/* That's all, stop editing! Happy blogging. */`.  (See [wp-config.php.txt](https://github.com/wp-cli/config-command/files/2205727/wp-config.php.txt), line 67. – Had to upload file as txt-file to attach it.)

Opening the website in the browser brings a white screen of death. `wp core install` with parameters doesn't get executed.

Looking at the file `templates/wp-config.mustache` I _assume_ the variable `{{extra-php}}` isn't used correctly.

Tested on local webserver (MAMP on MacOS, PHP 7.2.1), using WP-CLI 1.5.1.

**Comment by schlessera** [comment]
Thanks for the bug report, @pixolin!

I cannot replicate this on my system. Reading through the code, I can see that the `{{extra-php}}` variable should only be set if the `--extra-php` flag is being used.

Can you confirm that you did not use the `--extra-php` flag for the config generated above?

Also, can you check whether the project you're running this in contains a `wp-cli.yml` file that might have this `extra-php` setting included?

**Comment by pixolin** [comment]
I just followed the code example on https://developer.wordpress.org/cli/commands/config/create/ and created a `wp-config.php` using 
```
wp config create --dbname=testwpcli --dbuser=root --dbpass=root --extra-php <<PHP
define( 'WP_DEBUG', true );
define( 'WP_DEBUG_LOG', true );
PHP
```
In this case, the two lines for constants `WP_DEBUG` and `WP_DEBUG_LOG` get inserted *instead* of the word Array.

If I use the same command without paramater `--extra-php`, I again get a `wp-config.php` with a line showing the word `Array`.

**Comment by pixolin** [comment]
Today I learned about the `wp cli info` command and retrieving information about my install I saw, that I actually _did_ have a `wp-cli.yml`-file in a hidden directory `/Users/bego/.wp-cli/config.yml`.  I must have set up that file ages ago and didn't remember I had it. After removing that file, everything works as expected. Sorry for the inconvenience.

**Comment by schlessera** [comment]
Glad you could figure it out!

Maybe we should work on a troubleshooting guide that explains stuff like using `wp cli info` to figure out what config files are being loaded... 🤔
