### ISSUE TITLE
wildcard for alias (dynamic aliases)

### ISSUE THREAD

**Issue by drzraf** [wp-cli/config-command#75]
#58 is a case for dynamically generated `~/.wp-cli/config.yml`

Going further with WP instance mass-management, I'd like to know what do you think about the idea that alias support globbing string patterns and be provided as a variable to alias's directives.

For example:
```
'@ae-*':
  ssh: docker:phpfpm-projectone-{alias}/var/www
```
would support `wp @ae-us-master` bound to `docker:phpfpm-projectone-ae-us-master/var/www`
as well as `wp @ae-in-develop` bound to `docker:phpfpm-projectone-ae-in-develop/var/www`
etc...

**Comment by schlessera** [comment]
I think I (cautiously) like this idea.

Some observations:
- Would the wildcard also work in random locations? I.e., support something like this:
   ```
   '@*-dev':
     require: /some/folder/development-additions.php
   ```
- What happens with the `{alias}` placeholder in nested aliases? Multiple aliases will then be active.
- How are groups handled? How is `@all` handled? There's no list of possible values anymore. Are placeholder-aliases just ignored in these cases?
