### ISSUE TITLE
WordPress become blank page after setting WP_MEMORY_LIMIT

### ISSUE THREAD

**Issue by a2d8a4v** [wp-cli/config-command#84]
After I tried 
`wp config set WP_MEMORY_LIMIT 100M --raw --path=/path/to/wp/root --quiet --allow-root`
I found wp-cli will add one line like this below
`define( 'WP_MEMORY_LIMIT', 100M );`

But the wrong is that, 「100M」should be quoted like this:
`define( 'WP_MEMORY_LIMIT', '100M' );`
or WordPress could not figure out what we want to do, and then lead to error, even blank page.

Test environment: Ubuntu 18.04.2 LTS, WordPress 5.1, php 7.3, wp-cli 2

**Comment by fjarrett** [comment]
You may want to read over the docs again for the `set` command, specifically, the part about what `--raw` means.

**Comment by a2d8a4v** [comment]
OK, I got it! I shouldn't use --raw

**Comment by a2d8a4v** [comment]
Please close this issue for me, sorry for bothering you

**Comment by danielbachhuber** [comment]
No worries, thanks @a2d8a4v !
