### ISSUE TITLE
errors updating shuffle-salts

### ISSUE THREAD

**Issue by ibertrix** [wp-cli/config-command#92]
I run several wordpress sites and after a Wordpress meetup someone mentioned that it might be worth for security reasons to update salts in wp-config. I am running a script to run wp-cli config shuffle-salts. When most times is working I am finding out that sometimes there are lines that get parse errors similar to this one:

define( 'LOGGED_IN_SALT',   'BLABLABLA');'BLABLABLA');

so inserting some code right after ; and breaking website.

It has happened to me in several sites so maybe If I have to take into account something when issueing this command

**Comment by danielbachhuber** [comment]
Thanks for the report, @ibertrix !

Unfortunately, this will be difficult to fix without specific steps to reproduce. Feel free to stop by the `#cli` channel on [WordPress.org Slack](https://make.wordpress.org/chat/) if you'd like help debugging further.
