### ISSUE TITLE
`wp config create`: passwords with single quotes breaks wp-config.php

### ISSUE THREAD

**Issue by dvigueras** [wp-cli/config-command#93]
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

When creating a new `wp-config.php` file with a password containing single quotes, the resulting `wp-config.php` file is invalid and produces a PHP syntax error.

**Describe how other contributors can replicate this bug**

- Create a new Database and a new Database User (e.g.: wpdb / wpuser)
- Create a new directory (wordpress)
- Download WordPress (`wp core download ...`)
- Create config file with a password containing single quotes: `wp config create --dbname=wpdb --dbuser=wpuser --dbpass=".bWWd}6B3X E-gv9BYEjpH9 w+'Pq5" --dbhost=127.0.0.1`

`Success: Generated 'wp-config.php' file.`

Content of the `wp-config.php`:
```php
...
define( 'DB_PASSWORD', '.bWWd}6B3X E-gv9BYEjpH9 w+'Pq5' );
...
```

```bash
$ php -l wp-config.php
PHP Parse error:  syntax error, unexpected 'Pq5' (T_STRING), expecting ')' in wp-config.php on line 29
Errors parsing wp-config.php
```

**Describe what you would expect as the correct outcome**

The value of the `DB_PASSWORD` constant should be escaped:

`define( 'DB_PASSWORD', '.bWWd}6B3X E-gv9BYEjpH9 w+\'Pq5' );`

**Let us know what environment you are running this on**

```
wp cli info
OS:	Linux 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64
Shell:	/bin/bash
PHP binary:	/usr/bin/php7.3
PHP version:	7.3.7-1+ubuntu18.04.1+deb.sury.org+1
php.ini used:	/etc/php/7.3/cli/php.ini
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/home/site1/sites/wpapp/public
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version:	2.2.0
```

**Provide a possible solution**

A possible solution would be to escape the single quote character in the `wp-config.php` file.

**Comment by diegoturcios** [comment]
Not sure if this is related, but also when you run this in CLI also breaks it
`wp config set DB_PASSWORD "ViuytrhgfdN(DW*kb;" --path="."`
![image](https://user-images.githubusercontent.com/70163776/130257975-d11a0bab-0963-4f48-99eb-2368fc90d2cf.png)
