### ISSUE TITLE
`shuffle-salts` doesn't regenerate `WP_CACHE_KEY_SALT`

### ISSUE THREAD

**Issue by binaryfire** [wp-cli/config-command#96]
Hi guys

**Describe the current, buggy behavior**
Running **wp config shuffle-salts** regenerates all salts except WP_CACHE_KEY_SALT

**Describe what you would expect as the correct outcome**
All salts should be regenerated by the shuffle-salts command. 

**Possible solution**
Check if WP_CACHE_KEY_SALT is present, and if true then regenerate key

**Context**
I'm using a custom wp-config.php template with placeholders for deployment so I can't use **wp config create**. I'm using sed to replace database credential placeholders and and wp config shuffle-salts to add unique salts. This system works well except for the fact that WP_CACHE_KEY_SALT isn't shuffled. I realise WP_CACHE_KEY_SALT isn't in the standard wp-config.php file, however it is present in all wp-config.php files created with **wp config create** . Therefore I think it makes sense for wp config shuffle-salts to also handle its regeneration.

Cheers!

**Comment by schlessera** [comment]
I'm not sure we should shuffle the cache key salt by default, because:
- it will invalidate the entire caching subsystem, maybe leading to a cache stampede.
- it might be set to a very specific value to coordinate multiple servers using the same cache.

I'm open to adding this behind a separate flag, but I don't think it should be part of the default behavior.

**Comment by menathor** [comment]
@schlessera Didn't think of that, good point. Behind a flag would be great. But what about taking it a step further and adding a flag to generate a salt for anything? For example, setting a JWT secret: 

**wp config set JWT_SECRET --salt**

or to regenerate the cache key:

**wp config set WP_CACHE_KEY_SALT --salt**

**Comment by schlessera** [comment]
I like that idea! I'm not sure about the syntax, though, I don't like adding an arbitrary flag to `config set` like that.

How about this:

`wp config shuffle-salts [--key=<key>] [--force]`

`<key>` is the specific key to shuffle. `core-group` or something similar could be a value to denote the default ones, and it could be set as the default value for `--key` to cover BC.

`--force` would basically mean "update if it exists or create if it doesn't exist".

**Comment by menathor** [comment]
Nice! Would `--force` be necessary though? Specifying any key other than  `core-group` could either replace an existing key's value with a new salt, or create the key if it doesn't. Similar to how `wp config set` works.

**Comment by schlessera** [comment]
It's more about semantics: "shuffle" implies that there is something already there to shuffle.

**Comment by ingobaab** [comment]
I helped myself with first `wp config shuffle-salts` and then 
`wp config set WP_CACHE_KEY_SALT '$WP_CACHE_KEY_SALT'`
Is there a better (shorter) way?

**Comment by paulschreiber** [comment]
Hit this again today. Would very much like to be able to generate `WP_CACHE_KEY_SALT` with wp cli.

What do we need to do to unblock this task?

Core folks are aggressively nope-ing out on this one:
https://meta.trac.wordpress.org/ticket/3678
https://core.trac.wordpress.org/ticket/44425

**Comment by lukecav** [comment]
This would be very helpful to have included even if you had to include the key specifically when you ran the command.

`wp config shuffle-salts --key=WP_CACHE_KEY_SALT`

**Comment by tillkruss** [comment]
@lukecav has anyone opened a PR on this?

**Comment by lukecav** [comment]
@tillkruss Does not look like they have https://github.com/wp-cli/config-command/pulls

**Comment by schlessera** [comment]
I just added a PR that makes `shuffle-salts` accept positional arguments for cache keys to shuffle. So while this still does not shuffle the cache key salt by default (which I think is not a safe default as explained above), it allows you to shuffle it easily with the single command: `wp config shuffle-salt WP_CACHE_KEY_SALT`.

Adding `--force` will generate it as needed if it is not yet present.
