### ISSUE TITLE
Missing documentation: special flag `--anchor=EOF`

### ISSUE THREAD

**Issue by schlessera** [wp-cli/config-command#97]
In https://github.com/wp-cli/wp-config-transformer/pull/23 we added special behavior for the anchor selection to allow the user to specify the end of file.

This can be use by passing the special `EOF` value to the flag: `--anchor=EOF`.

We forgot to add documentation to the `config` command in all the places where an `--anchor` flag is accepted. This special case handling should be added to all the corresponding docblocks.

**Comment by spicecadet** [comment]
Pull request for this: https://github.com/wp-cli/config-command/pull/109
